### ISSUE TITLE
[Bug] White text color on white background

### ISSUE THREAD

**Issue by first087** [m-e-h/material-gaze#1]
When current page = sub menu in navigation menu. Text color is white on white background color.

Please fix.

**Comment by m-e-h** [comment]
Thanks @first087 . This makes sense now https://wordpress.org/support/topic/menu-current-link-color#post-7436032
I thought that user made his top bar white. Now I understand it's the submenus.

I'll fix it and update.

**Comment by first087** [comment]
I fixed it with custom css on my site.

``` css
#menu-primary ul.sub-menu > li.current-menu-item > a {
    color: #398E39;
}
```

See : http://www.artit-k.com/mobile/android/
